import express from "express";
import path from "path";
import dotenv from "dotenv";
import { createServer as createViteServer } from "vite";
import { GoogleGenAI, Type } from "@google/genai";
import {
  formatKnowledgeContext,
  KNOWLEDGE_BUILD,
  retrieveKnowledge,
} from "./src/lib/knowledgeRetrieval";
import {
  formatOfficialQuestionContext,
  getOfficialQuestion,
  getOfficialQuestionStoreHealth,
  queryOfficialQuestions,
  sampleOfficialQuestions,
} from "./src/lib/officialQuestions.server";
import { toLearnerFacingContent } from "./src/lib/learnerContent";

// Local development follows the README and keeps the Gemini key in .env.local.
// Load it first, then use .env only as a fallback for values not already set.
dotenv.config({ path: '.env.local' });
dotenv.config();

const app = express();
const PORT = 3000;

app.use(express.json());

// Lazy GoogleGenAI initialization helper
function getGenAIClient() {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    throw new Error("GEMINI_API_KEY environment variable is missing.");
  }
  return new GoogleGenAI({
    apiKey,
    httpOptions: {
      headers: {
        "User-Agent": "aistudio-build",
      },
    },
  });
}

// API Health Check
app.get("/api/health", (_req, res) => {
  res.json({ status: "ok", app: "SuVeCA Concursos 2.0", knowledgeBase: KNOWLEDGE_BUILD });
});

app.get("/api/knowledge/health", async (_req, res) => {
  try {
    const officialQuestions = await getOfficialQuestionStoreHealth();
    return res.json({ status: "ok", ...KNOWLEDGE_BUILD, officialQuestions });
  } catch (error: any) {
    return res.status(503).json({
      status: "error",
      component: "official-question-store",
      message: error.message,
    });
  }
});

const queryValue = (value: unknown) => typeof value === "string" ? value.trim() : undefined;
const questionFiltersFrom = (source: Record<string, unknown>) => ({
  moduleId: queryValue(source.moduleId),
  conceptId: queryValue(source.conceptId),
  topic: queryValue(source.topic),
  bank: queryValue(source.bank),
  year: queryValue(source.year) ? Number(source.year) : undefined,
  difficulty: queryValue(source.difficulty),
  query: queryValue(source.query),
});

// Official payloads are immutable. Filters and SuVeCA relations come from a
// separate derived index generated by kb:build.
app.get("/api/knowledge/questions", async (req, res) => {
  try {
    const filters = questionFiltersFrom(req.query as Record<string, unknown>);
    const offset = Math.max(0, Number(req.query.offset) || 0);
    const limit = Math.min(100, Math.max(1, Number(req.query.limit) || 20));
    return res.json(await queryOfficialQuestions(filters, { offset, limit }));
  } catch (error: any) {
    return res.status(500).json({ error: "Não foi possível consultar o corpus oficial.", details: error.message });
  }
});

app.post("/api/knowledge/questions/sample", async (req, res) => {
  try {
    const filters = questionFiltersFrom((req.body || {}) as Record<string, unknown>);
    const count = Math.min(50, Math.max(1, Number(req.body?.count) || 10));
    const questions = (await sampleOfficialQuestions(filters, count)).filter(Boolean);
    return res.json({ count: questions.length, questions });
  } catch (error: any) {
    return res.status(500).json({ error: "Não foi possível montar a amostra oficial.", details: error.message });
  }
});

app.get("/api/knowledge/questions/:questionId", async (req, res) => {
  try {
    const question = await getOfficialQuestion(req.params.questionId);
    if (!question) return res.status(404).json({ error: "Questão oficial não encontrada." });
    return res.json(question);
  } catch (error: any) {
    return res.status(500).json({ error: "Não foi possível carregar a questão oficial.", details: error.message });
  }
});

// API: Analyze sentence with SuVeCA method
app.post("/api/suveca/analyze", async (req, res) => {
  try {
    const { sentence, model } = req.body;
    if (!sentence || typeof sentence !== "string") {
      return res.status(400).json({ error: "Frase inválida para análise." });
    }

    const ai = getGenAIClient();
    const knowledgeContext = formatKnowledgeContext(
      retrieveKnowledge(`${sentence} sujeito verbo complemento sintaxe oração`, 3)
    );
    const prompt = `Analise a seguinte oração em português do Brasil aplicando rigorosamente o Método SuVeCA (Sujeito, Verbo, Complemento, Adjunto e Predicativo):

Frase: "${sentence}"

${knowledgeContext}

Forneça um JSON estruturado com os blocos sintáticos, classe gramatical de cada termo, ordem (direta ou inversa), voz verbal, explicação pedagógica para concursos públicos e os IDs das fontes efetivamente usadas. Não atribua a uma fonte a interpretação editorial própria do método.`;

    const selectedModel = model || "gemini-3.1-flash-lite";

    const response = await ai.models.generateContent({
      model: selectedModel,
      contents: prompt,
      config: {
        systemInstruction:
          "Você é um especialista em Sintaxe da Língua Portuguesa para concursos públicos e tutor do método SuVeCA. Use prioritariamente os perfis adjudicados da Base Canônica v3, aplique limites e exceções, diferencie sourceFacts de derivações SuVeCA e não invente proveniência.",
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            sentence: { type: Type.STRING },
            order: { type: Type.STRING, description: "Direta ou Inversa" },
            verbalVoice: { type: Type.STRING, description: "Ativa, Passiva Analítica, Passiva Sintética, Reflexiva" },
            blocks: {
              type: Type.ARRAY,
              items: {
                type: Type.OBJECT,
                properties: {
                  text: { type: Type.STRING },
                  category: {
                    type: Type.STRING,
                    description: "SUJEITO, VERBO, COMPLEMENTO, ADJUNTO_ADVERBIAL, ADJUNTO_ADNOMINAL, PREDICATIVO, CONECTOR, VOCATIVO, APOSTO",
                  },
                  shortLabel: { type: Type.STRING, description: "Su, Ve, C(OD), C(OI), Aadv, Aadn, Pred, etc." },
                  colorTag: { type: Type.STRING, description: "blue, emerald, amber, purple, rose, cyan, gray" },
                  morphology: { type: Type.STRING, description: "Classes morfológicas envolvidas" },
                  explanation: { type: Type.STRING, description: "Motivo sintático e regras para concursos" },
                },
                required: ["text", "category", "shortLabel", "explanation"],
              },
            },
            summaryExplanation: { type: Type.STRING, description: "Resumo pedagógico e atenção para concursos" },
            contestTips: {
              type: Type.ARRAY,
              items: { type: Type.STRING },
              description: "Pegadinhas ou detalhes cobrados pelas bancas (Cebraspe, FGV, FCC)",
            },
            knowledgeSources: {
              type: Type.ARRAY,
              items: { type: Type.STRING },
              description: "IDs no formato KB:uuid das fontes efetivamente usadas.",
            },
          },
          required: ["sentence", "order", "verbalVoice", "blocks", "summaryExplanation"],
        },
      },
    });

    const jsonStr = response.text || "{}";
    const data = JSON.parse(jsonStr);
    return res.json(data);
  } catch (error: any) {
    console.error("Erro na análise SuVeCA:", error);
    return res.status(500).json({
      error: "Não foi possível analisar a oração via IA no momento.",
      details: error.message,
    });
  }
});

// API: Ask Professor SuVeCA (AI Grammar Tutor)
app.post("/api/gemini/explain", async (req, res) => {
  try {
    const { question, context, history, model } = req.body || {};
    if (typeof question !== "string" || !question.trim()) {
      return res.status(400).json({ error: "Pergunta não informada." });
    }

    const safeQuestion = question.trim().slice(0, 4000);
    const safeContext = typeof context === "string"
      ? context.trim().slice(0, 800)
      : "Geral de Português para Concursos";
    const safeHistory = Array.isArray(history)
      ? history
          .slice(-6)
          .filter((message) => message && (message.role === "user" || message.role === "assistant") && typeof message.text === "string")
          .map((message) => ({ role: message.role as "user" | "assistant", text: message.text.trim().slice(0, 4000) }))
          .filter((message) => message.text)
      : [];
    const conversationContext = safeHistory.length
      ? safeHistory.map((message) => `${message.role === "user" ? "Aluno" : "Professor"}: ${message.text}`).join("\n\n")
      : "Sem mensagens anteriores relevantes.";

    const ai = getGenAIClient();
    const knowledgeContext = formatKnowledgeContext(
      retrieveKnowledge(`${safeContext} ${safeQuestion}`, 3)
    );
    const officialQuestionContext = await formatOfficialQuestionContext(`${safeContext} ${safeQuestion}`, 2);
    const prompt = `Contexto/Módulo: ${safeContext}

HISTÓRICO RECENTE:
${conversationContext}

DÚVIDA ATUAL DO ALUNO:
${safeQuestion}

${knowledgeContext}

${officialQuestionContext}

Produza answerMarkdown e sourceRefs separadamente.

REGRAS PARA answerMarkdown:
- Responda diretamente à dúvida atual levando em conta o histórico; não se apresente novamente.
- Explique o porquê, o teste mental repetível na prova e a regra decisiva.
- Quando útil, dê um exemplo positivo e um contrastivo e destaque a pegadinha típica.
- Diferencie eixos classificatórios distintos (por exemplo, impessoalidade e transitividade).
- Faça uma verificação de coerência: não apresente a mesma construção como certa e errada sob as mesmas condições.
- Use Markdown com títulos curtos, negrito, listas ou tabelas somente quando melhorarem a compreensão.
- Não inclua PASSAGE, QUESTION, KB, IDs, hashes ou referências técnicas no texto pedagógico.
- Se a base não sustentar uma afirmação específica, diga isso claramente em linguagem natural.

REGRAS PARA sourceRefs:
- Liste apenas os identificadores PASSAGE e QUESTION efetivamente usados.
- As referências são metadados internos e nunca devem ser explicadas dentro de answerMarkdown.
- Preserve o conteúdo oficial citado; não o corrija, reescreva nem atribua à SuVeCA.`;

    const selectedModel = model || "gemini-3.1-flash-lite";

    const response = await ai.models.generateContent({
      model: selectedModel,
      contents: prompt,
      config: {
        systemInstruction:
          "Você é o Professor SuVeCA, tutor ancorado na Base Canônica SuVeCA v3. Preserve a separação entre conhecimento validado e interpretação SuVeCA, aplique limites e exceções, responda com rigor pedagógico e mantenha toda proveniência exclusivamente em sourceRefs.",
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            answerMarkdown: {
              type: Type.STRING,
              description: "Resposta pedagógica em Markdown sem identificadores técnicos de fontes.",
            },
            sourceRefs: {
              type: Type.ARRAY,
              items: { type: Type.STRING },
              description: "Referências internas PASSAGE e QUESTION efetivamente utilizadas.",
            },
          },
          required: ["answerMarkdown", "sourceRefs"],
        },
      },
    });

    const data = JSON.parse(response.text || "{}");
    const answerMarkdown = toLearnerFacingContent(data.answerMarkdown);
    if (!answerMarkdown) throw new Error("O Professor não retornou conteúdo pedagógico válido.");
    const sourceRefs = Array.isArray(data.sourceRefs)
      ? data.sourceRefs.filter((reference: unknown) => typeof reference === "string" && /^(?:PASSAGE|QUESTION):/i.test(reference))
      : [];
    return res.json({ answerMarkdown, sourceRefs });
  } catch (error: any) {
    console.error("Erro no Professor SuVeCA:", error);
    return res.status(500).json({
      error: "Erro ao consultar o Professor SuVeCA.",
      details: error.message,
    });
  }
});

// API: Generate Custom Questões
app.post("/api/gemini/generate-questions", async (req, res) => {
  try {
    const { topic, bank, count, model } = req.body;
    const ai = getGenAIClient();
    const knowledgeContext = formatKnowledgeContext(
      retrieveKnowledge(`${topic || ''} ${bank || ''}`, 3)
    );
    const officialQuestionContext = await formatOfficialQuestionContext(`${topic || ''} ${bank || ''}`, 2);

    const prompt = `Gere ${count || 3} questões inéditas no estilo da banca ${bank || "CEBRASPE / FGV"} sobre o tema: "${topic || "Concordância e SuVeCA"}".

${knowledgeContext}

${officialQuestionContext}

As questões oficiais acima servem apenas como referência de incidência e formato. Não copie, corrija nem reescreva seus enunciados ou soluções. Forneça questões novas com enunciado, alternativas/opções ou julgamento Certo/Errado, resposta correta, comentário gramatical detalhado e sourceRefs separados. O comentário é conteúdo do aluno e não pode conter PASSAGE, QUESTION, KB ou IDs técnicos; as referências internas ficam exclusivamente em sourceRefs.`;

    const selectedModel = model || "gemini-3.1-flash-lite";

    const response = await ai.models.generateContent({
      model: selectedModel,
      contents: prompt,
      config: {
        systemInstruction: "Você é um elaborador de questões de Língua Portuguesa para concursos públicos.",
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            questions: {
              type: Type.ARRAY,
              items: {
                type: Type.OBJECT,
                properties: {
                  id: { type: Type.STRING },
                  type: { type: Type.STRING, description: "CERTO_ERRADO ou MULTIPLA_ESCOLHA" },
                  bank: { type: Type.STRING },
                  topic: { type: Type.STRING },
                  supportText: { type: Type.STRING, description: "Texto de apoio opcional" },
                  questionText: { type: Type.STRING },
                  options: {
                    type: Type.ARRAY,
                    items: {
                      type: Type.OBJECT,
                      properties: {
                        letter: { type: Type.STRING },
                        text: { type: Type.STRING },
                      },
                    },
                  },
                  correctAnswer: { type: Type.STRING, description: "C ou E se for Certo/Errado, ou A, B, C, D, E" },
                  commentary: { type: Type.STRING, description: "Comentário pedagógico completo com a regra decisiva" },
                  sourceRefs: {
                    type: Type.ARRAY,
                    items: { type: Type.STRING },
                    description: "Referências internas PASSAGE utilizadas na elaboração.",
                  },
                },
                required: ["id", "type", "questionText", "correctAnswer", "commentary", "sourceRefs"],
              },
            },
          },
          required: ["questions"],
        },
      },
    });

    const jsonStr = response.text || "{}";
    const data = JSON.parse(jsonStr);
    const questions = Array.isArray(data.questions)
      ? data.questions.map((question: any) => ({
          ...question,
          supportText: toLearnerFacingContent(question.supportText) || undefined,
          questionText: toLearnerFacingContent(question.questionText),
          commentary: toLearnerFacingContent(question.commentary),
          options: Array.isArray(question.options)
            ? question.options.map((option: any) => ({ ...option, text: toLearnerFacingContent(option.text) }))
            : question.options,
          sourceRefs: Array.isArray(question.sourceRefs)
            ? question.sourceRefs.filter((reference: unknown) => typeof reference === "string" && /^PASSAGE:/i.test(reference))
            : [],
        }))
      : [];
    return res.json({ questions });
  } catch (error: any) {
    console.error("Erro ao gerar questões:", error);
    return res.status(500).json({
      error: "Não foi possível gerar as questões no momento.",
      details: error.message,
    });
  }
});

// API: Generate active-recall flashcards from a Caderno de Erros entry
app.post("/api/gemini/generate-error-flashcards", async (req, res) => {
  try {
    const { error, count, model } = req.body || {};
    if (
      !error ||
      typeof error.conteudo !== "string" ||
      typeof error.erroCometido !== "string" ||
      typeof error.regraDecisiva !== "string"
    ) {
      return res.status(400).json({
        error: "Envie um registro válido do Caderno de Erros para criar os flashcards.",
      });
    }

    const cardCount = Math.min(Math.max(Number(count) || 2, 1), 4);
    const truncate = (value: string) => value.trim().slice(0, 2400);
    const ai = getGenAIClient();
    const knowledgeContext = formatKnowledgeContext(
      retrieveKnowledge(`${error.conteudo} ${error.regraDecisiva}`, 2)
    );
    const prompt = `Transforme o seguinte registro do Caderno de Erros em ${cardCount} flashcards curtos de revisão ativa.

Tópico: ${truncate(error.conteudo)}
Erro cometido: ${truncate(error.erroCometido)}
Regra decisiva: ${truncate(error.regraDecisiva)}
Exemplo de fixação: ${typeof error.novoExemplo === "string" ? truncate(error.novoExemplo) : "não informado"}

${knowledgeContext}

Para cada flashcard produza:
- front: pergunta curta de recuperação ativa;
- back: resposta objetiva para conferência rápida;
- hint: dica opcional que conduz ao raciocínio sem entregar a resposta;
- explanation: explicação detalhada com o porquê, teste mental, ao menos um exemplo, contraste quando útil e pegadinha de concurso;
- sourceRefs: referências PASSAGE efetivamente usadas, como metadados internos.

A explicação não deve apenas repetir o verso. Não invente regras que não estejam apoiadas no perfil adjudicado. Nenhum texto de front, back, hint ou explanation pode conter PASSAGE, QUESTION, KB, IDs ou referências técnicas; mantenha-os exclusivamente em sourceRefs.`;

    const response = await ai.models.generateContent({
      model: model || "gemini-3.1-flash-lite",
      contents: prompt,
      config: {
        systemInstruction:
          "Você é um professor de Língua Portuguesa para concursos. Crie flashcards claros, autocontidos e focados em revisar a Regra Decisiva usando o método SuVeCA.",
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            flashcards: {
              type: Type.ARRAY,
              items: {
                type: Type.OBJECT,
                properties: {
                  front: {
                    type: Type.STRING,
                    description: "Pergunta de recuperação ativa, em português do Brasil.",
                  },
                  back: {
                    type: Type.STRING,
                    description: "Resposta explicada, breve e correta.",
                  },
                  hint: {
                    type: Type.STRING,
                    description: "Dica curta opcional, sem entregar a resposta inteira.",
                  },
                  explanation: {
                    type: Type.STRING,
                    description: "Aprofundamento pedagógico com raciocínio, exemplo, contraste e pegadinha, sem IDs técnicos.",
                  },
                  sourceRefs: {
                    type: Type.ARRAY,
                    items: { type: Type.STRING },
                    description: "Referências internas PASSAGE efetivamente utilizadas.",
                  },
                },
                required: ["front", "back", "explanation", "sourceRefs"],
              },
            },
          },
          required: ["flashcards"],
        },
      },
    });

    const data = JSON.parse(response.text || "{}");
    const flashcards = Array.isArray(data.flashcards)
      ? data.flashcards.map((card: any) => ({
          front: toLearnerFacingContent(card.front),
          back: toLearnerFacingContent(card.back),
          hint: toLearnerFacingContent(card.hint) || undefined,
          explanation: toLearnerFacingContent(card.explanation),
          sourceRefs: Array.isArray(card.sourceRefs)
            ? card.sourceRefs.filter((reference: unknown) => typeof reference === "string" && /^PASSAGE:/i.test(reference))
            : [],
        })).filter((card: any) => card.front && card.back && card.explanation)
      : [];
    return res.json({ flashcards });
  } catch (error: any) {
    console.error("Erro ao gerar flashcards:", error);
    return res.status(500).json({
      error: "Não foi possível gerar flashcards via IA no momento.",
      details: error.message,
    });
  }
});

// Vite & Static file handling
async function startServer() {
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    app.get("*", (_req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`SuVeCA Server running on http://localhost:${PORT}`);
  });
}

startServer();
