/* AUTO-GENERATED by scripts/build-pedagogical-curriculum.mjs. */
export const OFFICIAL_SIMULADO_ANSWER_KEY = {
  "editorial-sim-01": "C",
  "editorial-sim-02": "D",
  "editorial-sim-03": "C",
  "editorial-sim-04": "C",
  "editorial-sim-05": "B",
  "editorial-sim-06": "C",
  "editorial-sim-07": "E",
  "editorial-sim-08": "A",
  "editorial-sim-09": "D",
  "editorial-sim-10": "E",
  "editorial-sim-11": "E",
  "editorial-sim-12": "C",
  "editorial-sim-13": "A",
  "editorial-sim-14": "A",
  "editorial-sim-15": "C",
  "editorial-sim-16": "C",
  "editorial-sim-17": "B",
  "editorial-sim-18": "D",
  "editorial-sim-19": "E",
  "editorial-sim-20": "C"
} as const;
export const OFFICIAL_SIMULADO_VERSION = 'editorial-simulado-f325f31b30b382a7';
