/* AUTO-GENERATED by scripts/build-deployment-shards.mjs. */
import { KNOWLEDGE_INDEX_PART_001 } from './knowledge-index/knowledge-index.part-001.generated';
import { KNOWLEDGE_INDEX_PART_002 } from './knowledge-index/knowledge-index.part-002.generated';
import { KNOWLEDGE_INDEX_PART_003 } from './knowledge-index/knowledge-index.part-003.generated';
import { KNOWLEDGE_INDEX_PART_004 } from './knowledge-index/knowledge-index.part-004.generated';

export const KNOWLEDGE_BUILD = {
  "schemaVersion": "2.0.0",
  "buildId": "a4ab314ea482d506",
  "corpusDigest": "dd1356c9b242a197a1956c8c5500c545801daf7ea814dfc4852ffee585518e75",
  "sourceCount": 284,
  "semanticStatus": "passed",
  "officialQuestionCount": 372,
  "officialQuestionDigest": "2630a301053ad29099abcdb15848c8e8910ca47afdcbae88562c068f37df8b11"
} as const;

export const KNOWLEDGE_INDEX = [
  ...KNOWLEDGE_INDEX_PART_001,
  ...KNOWLEDGE_INDEX_PART_002,
  ...KNOWLEDGE_INDEX_PART_003,
  ...KNOWLEDGE_INDEX_PART_004,
] as const;
