/* AUTO-GENERATED by scripts/build-pedagogical-curriculum.mjs. */
export const PEDAGOGICAL_KNOWLEDGE_BUILD = {
  "schemaVersion": "4.2.0",
  "buildId": "bd540dafde969016",
  "sourceCount": 15,
  "unitCount": 115,
  "semanticStatus": "passed",
  "mediaDependencies": 0
} as const;
