/* AUTO-GENERATED by scripts/build-pedagogical-macro-index.mjs. */
import type {
  PedagogicalMacroAdaptiveLink,
  PedagogicalMacroIndexEntry,
} from '../types/pedagogicalMacro';

/**
 * Bootstrap placeholder. The build script replaces it as soon as the
 * published factory catalog is present; --check fails while it is stale.
 */
export const PEDAGOGICAL_MACRO_CATALOG_ID = '';
export const PEDAGOGICAL_MACRO_INDEX = [] as const satisfies readonly PedagogicalMacroIndexEntry[];
export const PEDAGOGICAL_MACRO_ADAPTIVE_LINKS = [] as const satisfies readonly PedagogicalMacroAdaptiveLink[];
