/* AUTO-GENERATED by scripts/build-pedagogical-curriculum.mjs. */
export const PEDAGOGICAL_KNOWLEDGE_BUILD = {
  "schemaVersion": "4.2.0",
  "buildId": "c18ca5159d1a27c2",
  "contentVersion": "2026.08.3",
  "sourceCount": 15,
  "unitCount": 115,
  "semanticStatus": "passed",
  "mediaDependencies": 0
} as const;
